### ISSUE TITLE
Dragging, focusing and updating in SwiftUI

### ISSUE THREAD

**Issue by geodesicer** [objcio/thinking-in-swiftui-qa#1]
Hi there,

I made a simple public project around dragging views around in SwiftUI. It contains simple stuff, but with iOS 17 there is the focus mechanism explained in the "The SwiftUI cookbook for focus" and I was trying to go directly into editing a TextField content from a LongPress gesture. Not quite clear how to get that working. 

The other thing that was difficult is to update a view "live" while dragging a subview, and a clarification on how to best solve that. I used FramePreferenceKey and could not get that to work either, so had to have a "parallell" @Binding to enable the "live" update.

The github repository is at "geodesicer/VisualEditor" and the main app contains different alternatives.

**Comment by floriankugler** [comment]
@geodesicer Can you elaborate what you're trying to do with the "live" update while dragging? Do you have a subview with a drag gesture, and you want to update the position of a parent of this view when the user drags? If you could paste in a short code sample, that would be super helpful.

**Comment by geodesicer** [comment]
Hi Florian,

you can see a lot of examples in my project @github


geodesicer/VisualEditor

It should be public access.


Code extracted:

There is 6 different examples I tried out:

VBoxesAndLines

This is simply two boxes with lines attached, and where you can add another box with a line with a double click. A longpress edit in one of the boxes makes it editable.

Question: How to focus directly into a TextField so you can start typing directly, this in iOS 17 and its new Focus functionality?

VDragAndIntersect1

VDragAndIntersect2

VUsingPreferenceKey

Different way to update back into the parent view using PreferenceKey’s, but only working when finishing the drag, tested by intersection.

Question: Can you use PreferenceKey to do ”live” update?

VIntersectingRects

Got ”live” updating in the parent view working by testing intersections of subview's

Question: Is this a hack or is this the way you have to do it?

@main
struct VisualEditorApp: App {
    var body: some Scene {
        WindowGroup {
            //VBoxesAndLines()
            //VDragAndIntersect1()
            //VDragAndIntersect2()
            //VUsingPreferenceKey()
            //VUpdateDraggableLocation()
            VIntersectingRects()
        }
    }
}


Main view for v´VIntersectingRects

typealias TPointColor = (point: CGPoint, color: Color)

struct VIntersectingRects: View {
    @GestureState private var dragState = EDragState.inactive
    //var localCoordingateSpace = NamedCoordinateSpace()

    @State public var positions: [
        TPointColor] = [
            (CGPoint(x: 20, y: 20), randomColor()),
            //(CGPoint(x: 20, y: 140), randomColor()),
            //(CGPoint(x: 20, y: 260), randomColor()),
            (CGPoint(x: 20, y: 380), randomColor()),
            //(CGPoint(x: 140, y: 20), randomColor()),
            (CGPoint(x: 140, y: 140), randomColor()),
            (CGPoint(x: 140, y: 260), randomColor()),
            //(CGPoint(x: 140, y: 380), randomColor()),
            //(CGPoint(x: 260, y: 20), randomColor()),
            (CGPoint(x: 260, y: 140), randomColor()),
            (CGPoint(x: 260, y: 260), randomColor()),
            //(CGPoint(x: 260, y: 380), randomColor()),
            (CGPoint(x: 380, y: 20), randomColor()),
            //(CGPoint(x: 380, y: 140), randomColor()),
            //(CGPoint(x: 380, y: 260), randomColor()),
            (CGPoint(x: 380, y: 380), randomColor()),
       ]
            
    var body: some View {
        VStack {
            Rectangle()
                .fill(isIntersecting() ? Color.green : Color.red)
                .frame(width: 100, height: 100)
            ZStack {
                ForEach(positions.indices, id: \.self) { index in
                    VDraggableRect3(bPos: $positions[index].point, color: positions[index].color)
                }
            }
            Spacer()
        }
        //.frame(width: 500, height: 500)
    }
    
    func isIntersecting() -> Bool  {
        var isIntersecting = false
        
        for primary in positions {
            let first = CGRect(origin: CGPoint(x: primary.point.x, y: primary.point.y)  , size: CGSize(width: 100, height: 100))

            for secondary in positions.dropFirst() {
                let second = CGRect(origin: CGPoint(x: secondary.point.x, y: secondary.point.y), size: CGSize(width: 100, height: 100))

                if primary != secondary {
                    isIntersecting = isIntersecting ? true : first.intersects(second)
                    
                    if isIntersecting { break }
                    //print("primary = \(primary)")
                    //print("first = \(first)")
                    //print("secondary = \(secondary)")
                    //print("second = \(second)")
               }
            }
            
            if isIntersecting { break }
        }
        
        return isIntersecting
    }
    
}

func randomColor() -> Color {
    let red = Double.random(in: 0..<1)
    let green = Double.random(in: 0..<1)
    let blue = Double.random(in: 0..<1)
    return Color(red: red, green: green, blue: blue, opacity: 1)
}


and the subview VDraggableRect3


struct VDraggableRect3: View {
    @GestureState public var dragState = EDragState.inactive
    @Binding var bPos: CGPoint
    @State private var pos = CGPoint.zero
    var color: Color
    
    var body: some View {
         return Rectangle()
                .fill(color)
                .frame(width: 100, height: 100)
                .border(Color.black)
                .offset(x: self.pos.x + self.dragState.translation.width, y: self.pos.y + self.dragState.translation.height)
                .gesture(DragGesture()
                    .updating($dragState) { (value, state, transaction) in
                        state = .dragging(translation: value.translation)
                        //print("state = \(state)'")
                    }
                    .onChanged { value in
                        self.bPos.x = self.pos.x + value.translation.width
                        self.bPos.y = self.pos.y + value.translation.height
                        //print("self.bPos: \(value.translation.description)")
                    }
                    .onEnded { value in
                        self.pos.x += value.translation.width
                        self.pos.y += value.translation.height
                    }
                )
                .onAppear() {
                    pos = bPos
                }
    }
}


Hope that clarifies my question(s).

Really trying to understand SwiftUI now that it seems to have become more production ready,
so thats wjy I am involving myself more and so looking forward to your book.


H. Ulf
