### ISSUE TITLE
Backward compatibility

### ISSUE THREAD

**Issue by iltercengiz** [objcio/thinking-in-swiftui-qa#10]
My understanding is that the new observation approach and the reduction in SwiftUI property wrappers (the fact that we need only `@State` and `@Environment` from now on) are only available if we're targeting iOS 17 and aligned releases. Given that macros are a Swift feature, would it be possible to use these if we are targeting earlier versions (inlinable?) or implement these ourselves?

**Comment by chriseidhof** [comment]
Hey @iltercengiz, we actually just answered this in the previous Q&A, showing how we could somehow hack this together. It's definitely possible to use some of those features but it's not going to be as nice as integrating this into SwiftUI directly (which only Apple can do).

**Comment by iltercengiz** [comment]
I better watch that session then, thanks for answering 🙂
