### ISSUE TITLE
.tag(_:)

### ISSUE THREAD

**Issue by emefde** [objcio/thinking-in-swiftui-qa#12]
Hi all.

I've been wondering if this view tagging is necessary. 
On page 37 related to the ObservedObject there's this code snippet where Picker is created and Text views are being tagged and from what I understand, reading the documentation, since the selection is non-optional String and explicit id in the ForEach is also a String there's no need for view tagging - in this particular example.

Is my thinking correct?

Have a great Friday :)

**Comment by floriankugler** [comment]
Thanks for the suggestion, we'll take a look at that!

**Comment by chriseidhof** [comment]
You're correct, we will fix this in the book. We also covered this in the Jul 7 Q&A.

**Comment by emefde** [comment]
Thank you Chris. Yup, I'm here watching and listening :)
