### ISSUE TITLE
manual Binding

### ISSUE THREAD

**Issue by emefde** [objcio/thinking-in-swiftui-qa#13]
Hi! Hope everyones having a nice Saturday :)

I've been doing a code along while reading the book and when I got to this example of constructing a Binding manually it did not compile so I turned to @State example few pages earlier and I saw that setter is annotated with nonmutating and so I did the same for our custom Binding and it worked. I checked @Bindings definition and it in fact has

```
    public var wrappedValue: Value { get nonmutating set }
```

Could you maybe elaborate more on this? Myabe you have an idea what's happening under the hood? Why the nonmutating keyword is used here? 

This also got me thinking that I don't really know how SwiftUI handles properties that are not annotated with property wrappers. Because for everything else there's got to be some reference-based storage going on.

PS. 
I know that live was yesterday but I only just got to that part, hope that's ok.
If not, please ignore and close.

**Comment by floriankugler** [comment]
We've talked about it in this Q&A: https://www.youtube.com/watch?v=MRuRhj3dnm8
