### ISSUE TITLE
Using environment in StateObject

### ISSUE THREAD

**Issue by dc-nrx** [objcio/thinking-in-swiftui-qa#14]
Hey Chris & Florian,

I hope you're both well!

With the upcoming stream on environment-related topics, I've been pondering over the possibility of injecting dependencies, be it values or objects, directly from the environment into the view's state/stateObject (rather than into the view itself). It seems like it might be similar to how SwiftUI's FetchRequest works, utilizing the managed object context from the env under the hood. Would that be something that can (and should) be implemented?

I also have a broader conceptual question in mind regarding this matter: would you perhaps have a moment to share your "big picture" vision of SwiftUI app architecture? I mean, the Apple guys, whom we supposedly should look up to, seem to heavily abuse singletones; or stuff things like NSManagedObject's right into the view layer; or do other weird things. On the other hand, the usual MVVM seem to fit kind of weird into SwiftUI - so I'm not even sure whether it truly belongs there. 

As far as I understand, the topic is not going to be specifically covered in the 2nd edition of the book, so I decided to try asking about it here.

If time is too short to cover it during the stream - maybe you have any recommended articles on the subject? I've seen plenty of the kind myself - but I would much prefer to trust your judgment on this, especially taking into account the gravity of the question; and the risk of picking a wrong idea without having experience it the area.

Thank you for taking the time to read this, and see you on the next stream! :)

Cheers,
Dima.

**Comment by floriankugler** [comment]
We've talked about it in this Q&A: https://www.youtube.com/watch?v=MRuRhj3dnm8
