### ISSUE TITLE
There is no future for Combine, can be Observable framework generally used for observing?

### ISSUE THREAD

**Issue by hibernat** [objcio/thinking-in-swiftui-qa#15]
Hi,

I am a big fan of Combine, however the structured concurrency in Swift is going to replace it. Reasoning:
- there is no compile time race condition check for Combine, async/await has this feature
- Combine removal from SwiftUI internal implementation clearly shows the way - no bright future for Combine
- Swift 6, actors, (distributed actors) etc.

However, the observation pattern is useful, that I just look for (nice) way how to subscribe for change without Combine's publishers. Could the new Observation framework be the right tool for general observations? Something that is fine with "Strict Concurrency Checking" for Swift 5.9 and beyond.

**Comment by floriankugler** [comment]
We've talked about it in this Q&A: https://www.youtube.com/watch?v=MRuRhj3dnm8
