### ISSUE TITLE
@Observable + @Environment + @Bindable

### ISSUE THREAD

**Issue by davidungar** [objcio/thinking-in-swiftui-qa#16]
How do I combine @Environment + @Bindable for an @Observable class?
Quick example: (written in a hurry)
@Observable class Holder { var x: Bool = false} // DOESN"T WORK
(Environment stuff for Holder>
class V: View {
@Bindable @Environment(\.holder) var holder
var body: some View {
  // need a binding for holder.x
}

**Comment by floriankugler** [comment]
We've talked about it in this episode: https://www.youtube.com/watch?v=MRuRhj3dnm8
