### ISSUE TITLE
problem with the Bookmark example

### ISSUE THREAD

**Issue by lapalme** [objcio/thinking-in-swiftui-qa#18]
On page 53, you present an example of a Bookmark shape for which you show how make sure that it keeps the same aspect ratio.

I have been trying to make it work, but I do not know where to put the `sizeThatFits` function so that it is called to guarantee the aspect ratio.

When i put the function within the `Bookmark` struct it is never called.

If I add it as an extension to `Shape` (which is probably the right thing to do), then the compiler returns the error:
      `Compiling failed: replaced function 'sizeThatFits' is not marked dynamic`

I use the Deployment target: 16.4 in Xcode 14.3.1

What do you suggest?
thanks
Guy

**Comment by lapalme** [comment]
Thanks for answering this issue by giving a complete example of a call to `sizeThatFits` during your last video.

I finally managed to find why my function was not called. To test it by _changing_ the size of the bookmark, I had used `.size()` which in fact short-circuits the call to `sizeThatFits` which makes sense in hindsight... Looking a few pages later in the book, I saw that I should use instead `.frame()` to define the size of the bookmark to be adjusted.

I am giving here the complete example (with print statements to follow the calls), in case it might be useful to others. Note that `.stroke()` must be called in order to get what is shown in the book. Otherwise, the bookmark is filled in black.

```swift
 extension CGRect {
      subscript(_ point: UnitPoint) -> CGPoint {
          CGPoint(x: minX + width*point.x, y: minY + height*point.y) }
  }
  
  struct Bookmark: Shape {
      func sizeThatFits(_ proposal: ProposedViewSize) -> CGSize {
          var result = proposal.replacingUnspecifiedDimensions()
          let ratio: CGFloat = 2/3
          let newWidth = ratio * result.height
          if newWidth <= result.width {
              result.width = newWidth
          } else {
              result.height = result.width / ratio
          }
          print("Bookmark.sizeThatFits:\(proposal.width!),\(proposal.height!)=>\(result.width),\(result.height)")
          return result
      }
      
      func path(in rect: CGRect) -> Path {
          let _ = print("path")
          return Path { p in
              p.move(to: rect[.topLeading])
              p.addLines([
                  rect[.bottomLeading], rect[.init(x: 0.5, y: 0.8)],
                  rect[.bottomTrailing], rect[.topTrailing], rect[.topLeading]
              ])
              p.closeSubpath()
          }
      }
  }
  
  struct ContentView: View {
      var body: some View {
          let _ = print("content view")
          Bookmark()
  //            .size(width:300,height:100) // comment to call sizeThatFits
              .stroke(.black,lineWidth: 3)
              .frame(width: 300, height:100)
      }
  }
```

Guy
PS: it would be great if there was an easy way of copying code snippets from the PDF. Currently, copying confuses formatting and some words are "lost" because of ligatures: eg. "float" becomes "??oat"

**Comment by floriankugler** [comment]
@lapalme Glad you got it working, and thanks for the feedback!
