### ISSUE TITLE
safe area

### ISSUE THREAD

**Issue by km3h** [objcio/thinking-in-swiftui-qa#19]
how is the safe area propogated down to children `Views`?  e.g. If a child view in a `VStack` is modified with `ignoresSafeArea` how does that change `VStack's` layout process?

**Comment by chriseidhof** [comment]
We answered this in today's q&a!

**Comment by chriseidhof** [comment]
Hey @km3h I also wrote up a short blog post with the answer, hope that helps! https://chris.eidhof.nl/post/visualize-swiftui-safe-area/
