### ISSUE TITLE
Rotating effect animation

### ISSUE THREAD

**Issue by alexito4** [objcio/thinking-in-swiftui-qa#2]
This is something that I've been wondering for a while. 

How can we animate a rotation effect, but making sure that when the animation stops it completes the rotation instead of coming back in the opposite clockwise direction?

Notice in the video when the loading stops the animation goes back for a bit to find its resting place. 

https://github.com/objcio/thinking-in-swiftui-qa/assets/750912/ef444a92-856c-4698-953a-dbdde32d634f

I've hacked a solution with the completion callback (recursively starting animations) but is not as nice cause there is a delay between them. 

I wonder if there is some animatable data trick to be pulled of here? I vaguely remember seeing something in one of your videos, maybe you can point me in the right direction ^^

Cheers, excited for the Q&A

**Comment by chriseidhof** [comment]
I don't think there's a simple beautiful solution but we do have one without completion handlers, we'll show it tonight!
