### ISSUE TITLE
frame(maxHeight:) and frame(minHeight:)

### ISSUE THREAD

**Issue by km3h** [objcio/thinking-in-swiftui-qa#21]
Is there something that can be said about these apis regarding their specific use cases? E.g. What solutions do they provide that other apis in SwiftUI do not. Sometimes I find them confusing and not able to apply them effectively.

The way I understand it is that these apis function as below but what does that mean 😄 

frame(maxHeight: x)'s height is:
min(x, max(proposedHeight, childHeight)

And

frame(minHeight: y)'s height is:
max(y, min(proposedHeight, childReportedHeight))

**Comment by chriseidhof** [comment]
We tried to cover this in the last Q&A and in the book as well. Hope that helps! https://www.youtube.com/watch?v=p14PG0bBvu8
