### ISSUE TITLE
Best practices for views working on iOS and macOS

### ISSUE THREAD

**Issue by chbeer** [objcio/thinking-in-swiftui-qa#22]
Especially getting good looking, well working Form views for both iOS and macOS without having two distinct views and without cluttering the view code with a lot of "if"s.

Especially Form views with:
- Sections on iOS but not on macOS
- Picker
- Buttons

**Comment by chriseidhof** [comment]
We didn't have a very good answer to this question, but we did try to answer it here: https://www.youtube.com/watch?v=p14PG0bBvu8
