### ISSUE TITLE
Dark theme for the book

### ISSUE THREAD

**Issue by andreybog** [objcio/thinking-in-swiftui-qa#23]
In the [Thinking in SwiftUI Q&A #5](https://www.youtube.com/watch?v=2JP0Of8PxyE) episode, you said that there will be no other book format other than PDF.

Is it possible to generate PDF with a dark theme?

**Comment by chriseidhof** [comment]
Hey @andreybog, at the moment we don't have this planned at all. Great idea though, we'll definitely consider this again when we do further updates.
