### ISSUE TITLE
Improving performance in SwiftUI

### ISSUE THREAD

**Issue by liorazi** [objcio/thinking-in-swiftui-qa#4]
What is the best methods/tools you recommend for to improving SwiftUI performance?

**Comment by chriseidhof** [comment]
Hi,

could you be more specific? Performance is a big topic and there isn't one right answer to every problem. Are you facing any specific problems?

Thanks!

**Comment by liorazi** [comment]
Sure, the topic in SwiftUI Performance i'd be happy to hear more about is how to minimize SwiftUI View redraws.
I know that there is a Xcode instrument that can help with that but maybe there are more methods/ways you guys can recommend, that will be great.
