### ISSUE TITLE
Binding Transformation

### ISSUE THREAD

**Issue by jbrunhuber** [objcio/thinking-in-swiftui-qa#5]
Hi 👋 I was wondering if there's a way to transform associated values in enum bindings and pass them to other views.

**The Problem**
Given that I have a list of items that are wrapped in a state enum

```swift
struct WishlistItem: Identifiable {
    let id = UUID()
    var name: String
    var description: String
}

enum State {
        case loading
        case error
        case finished([WishlistItem])
}
```

When the items are loaded (e. g. from the network), I want to display them in a List.
From there, I want to have the ability to edit those items in a different SwiftUI view. Therefore, I have to pass a `Binding` of the item to the view.

```swift
NavigationLink(item.name, destination: EditView(wishlistItem: Binding(get: {
                            return item
                        }, set: { value, transaction in
                            var mutable = items
                            if let idx = mutable.firstIndex(where: {
                                $0.id == item.id
                            }) {
                                mutable[idx] = value
                            }
                            wishlistModel.state = .finished(mutable)
                        })))
```

This works, but it has a lot of boilerplate code, which makes my view very complex.

**Possible solutions**
- I was thinking about a freestanding expression macro that could generate the initialization code for us. [Without having the possibility to link to certain enum cases](https://forums.swift.org/t/discussion-inclusion-of-casepaths-into-the-language/53024), we could use a generic enum (like `State<T>`) for that the macro would always generate code for the `.finished(T)` case.
- Maybe we could write a custom Binding or an extension to Binding and use an attached macro with a member role to generate the initializer for us.

These are just some random ideas using some iOS17 features. Maybe there's an easier approach to this common problem.

I created a demo application with my basic approach here: https://github.com/jbrunhuber/wwdc-wishlist

Kind regards and greetings to Florian from the team at HUK-Coburg.
Josh

**Comment by chriseidhof** [comment]
I wonder if you could take a two-step approach:

- I'd first write a way to get the `[WishlistItem]` out of the enum. Possibly using something like [case paths](https://github.com/pointfreeco/swift-case-paths) or a custom macro
- Second, the `List` has an initializer that takes an array of identifiable data and a body closure that has a binding to a specific element, [like this](https://developer.apple.com/documentation/swiftui/list/init(_:selection:rowcontent:)-3wghd) .

Let me know if that helps. I'll have a look at how hard it is to create that macro!

**Comment by jbrunhuber** [comment]
Hi @chriseidhof, thanks for your reply. I was thinking of wrapping the binding transformation in a separate View which would look something like this: 

```swift
struct StateView<LoadingContent: View, ErrorContent: View, Content: View>: View {
    @Binding
    var state: WishlistModel.State
    
    let loadingView: LoadingContent
    let errorView: ErrorContent
    let contentView: (Binding<[WishlistItem]>) -> Content
    
    init(state: Binding<WishlistModel.State>,
         @ViewBuilder loadingView: () -> LoadingContent,
         @ViewBuilder errorView: () -> ErrorContent,
         @ViewBuilder contentView: @escaping (Binding<[WishlistItem]>) -> Content) {
        self._state = state
        self.loadingView = loadingView()
        self.errorView = errorView()
        self.contentView = contentView
    }
   
    var body: some View {
        switch state {
        case .loading:
            loadingView
        case .error:
            errorView
        case .finished(let list):
            contentView(
                Binding(get: {
                    return list
                }, set: { newValue, _ in
                    state = .finished(newValue)
                })
            )
        }
    }
}
```

This way I can use the `List` with the the `Binding<[WishlistItem]>` as parameter like you mentioned. While this would work fine for this simple example, it would require a separate wrapper view for each State-implementation. 

I also tried using a generic `GenericState<T>` enum (to use across the whole project), but this wasn't possible, because my wrapper view relies on the exact type information of the associated value.

I guess the easiest (and most expressive) way of solving this problem would be to use some 3rd party library (like `IfCaseLet` and CasePaths from the PointFree Navigation Library). However I was curious if there would be a simple way utilising Bindings to make a small wrapper by myself.

**Comment by chriseidhof** [comment]
I'm not sure if I understand it completely yet :). 

The `StateView` approach is also possible, even with `GenericState<T>` if you add `T` as a generic parameter to the `StateView`:

```swift
struct StateView<Payload, LoadingContent: View, ErrorContent: View, Content: View>: View {
    @Binding
    var state: MyState<Payload>

    @ViewBuilder var loadingView: LoadingContent
    @ViewBuilder var errorView: ErrorContent
    @ViewBuilder var contentView: (Binding<Payload>) -> Content

    var body: some View {
        switch state {
        case .loading:
            loadingView
        case .error:
            errorView
        case .finished(let list):
            contentView(
                Binding(get: {
                    return list
                }, set: { newValue, _ in
                    state = .finished(newValue)
                })
            )
        }
    }
}
```

**Comment by jbrunhuber** [comment]
@chriseidhof Oh, I forgot to replace a `[WishlistItem]` with `Payload` and misinterpreted the error message 🤦‍♂️ Now it works 👍
